### ISSUE TITLE
Can we use an application registration and what permissions are needed ?

### ISSUE THREAD

**Issue by Voxxie** [erwinpaal/teams-wallboard#1]
Hi,

We want to use an application registration to query the call queues.
Do you know what permissions are needed to make it work ? (if its possible) 

Currently we are getting: 
```
Microsoft.Teams.ConfigAPI.Cmdlets.internal\Get-CsCallQueue : Powershell administered domain is unexpectedly null/empty
At C:\Program Files\WindowsPowerShell\Modules\MicrosoftTeams\4.9.1\custom\Merged_custom_PsExt.ps1:4502 char:13
+             $result = Microsoft.Teams.ConfigAPI.Cmdlets.internal\Get- ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-CsCallQueue_Get], ArgumentException
    + FullyQualifiedErrorId : Microsoft.Teams.ConfigAPI.Cmdlets.Generated.Cmdlets.GetCsCallQueue_Get
```

**Comment by erwinpaal** [comment]
Yes, that's possible and also how I do it. You can use certificate based authentication and assign the "Global Reader" role (least privileged in this case) to the app registration you created. Make sure to assign it from "Roles and administrators" in Azure AD, not from "Roles and administrators" in the enterprise application/app registration (it's different). If you need more info, let me know!

**Comment by Voxxie** [comment]
Hi Erwin,

Error changed to: 

```
Microsoft.Teams.ConfigAPI.Cmdlets.internal\Get-CsCallQueue : Access Denied.
At C:\Program Files\WindowsPowerShell\Modules\MicrosoftTeams\4.9.1\custom\Merged_custom_PsExt.ps1:4502 char:13
+             $result = Microsoft.Teams.ConfigAPI.Cmdlets.internal\Get- ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: ({ Identity = Da...dObos = False }:<>f__AnonymousType22`2) [Get-CsCallQueue_Get1], UndeclaredResponseException
    + FullyQualifiedErrorId : Forbidden,Microsoft.Teams.ConfigAPI.Cmdlets.Generated.Cmdlets.GetCsCallQueue_Get1
```

Do we need more API permissions?

**Comment by erwinpaal** [comment]
Does the `Connect-MicrosoftTeams` cmdlet show any errors?

**Comment by Voxxie** [comment]
No, only the Get-CsCallQueue

**Comment by erwinpaal** [comment]
Can you verify if there are succesful sign-ins with the service princial?
![2023-06-06 17_30_32-Teams Wallboard - Microsoft Azure](https://github.com/erwinpaal/teams-wallboard/assets/28626836/10d5dfad-5fc4-4240-9e02-7c78c34988d1)

And can you also check if the Global Reader role is properly assigned?
![2023-06-06 17_34_51-Global Reader - Microsoft Azure](https://github.com/erwinpaal/teams-wallboard/assets/28626836/c2ff9b35-bfdf-4c0b-9243-e605b21a2568)

**Comment by Voxxie** [comment]
Good news,   without changing anything today it works fine! 
So my guess is that it took some time to get the correct permissions. 

Thank you for your support.

**Comment by erwinpaal** [comment]
Great!
